#ifndef CONSTANTS
#define CONSTANTS
using namespace std;
//canIDs


//thresholds
/*should be used for checking whether a subsystem is within the healthy limit
 i.e. current is less than 50 or some other number*/



 //ERRORS
string ERROR_HIGH_CELL_TEMP = "WARNING: CELL TEMPERATURE HIGH, LIMITING POWER DRAW.\n";
string ERROR_CRITICAL_CELL_TEMP = "CRITICAL: CELL TEMP VERY HIGH, SHUTTING DOWN.\n";
string ERROR_LOW_CELL_TEMP = "WARNING: CELL TEMPERATURE LOW.\n";
string ERROR_NO_CURRENT_DTI = "WARNING: NO CURRENT TO DTI MC.\n";
string ERROR_APPS_BSPD = "WARNING: POWER LIMITED: APPS/BSPD ENGAGED BRAKE & THROTTLE\n";
string ERROR_THROTTLE_SIGNAL = "CRITICAL: THROTTLE SIGNAL UNRESPONSIVE. FIX\n";
string ERROR_MOTOR_TEMP =  "WARNING: MOTOR TEMP HIGH, LIMITING POWER DRAW\n";
string ERROR_CRITICAL_MOTOR_TEMP = "CRITICAL: MOTOR TEMP VERY HIGH, SHUTTING DOWN\n";
string ERROR_IMD_FAULT = "CRITICAL: IMD FAULT CHASSIS POSSIBLY ENERGIZED. EXIT VEHICLE.\n";






const int VALUE_CURRENT_MAX = 0;
const byte VALUE_BAT_TEMP_MAX = 0;
const byte VALUE_BAT_TEMP_MIN = 0;
const int VALUE_MOT_TEMP_MAX = 0;
const int VALUE_MOT_TEMP_MIN = 0;
const float VALUE_NO_CURRENT = 0;
const float VALUE_APPS_BSPD_THROTTLE = 0.25;
const int VALUE_MIN_BRAKE_PRESSURE = 0;
const float VALUE_MIN_CURRENT_THRESHOLD = 0;
const int VALUE_HARD_BRAKE_LIMIT = 0;
const float VALUE_APPS_UNRESPONSIVE_MAX = 0;
const byte VALUE_CRITICAL_MOTOR_TEMP = 0;
const float VALUE_MIN_RESPONSIVE_CURRENT_MOTOR = 0;
const float VALUE_DTI_CURRENT_THRESHOLD = 0;
const float VALUE_G_FORCE_LIMIT = 0;
const int VALUE_OVERHEAT_CURRENT_LIMIT = 0;
const byte VALUE_CRITICAL_BATTERY_TEMP_HIGH = 0;
const float VALUE_MAX_CURRENT_DRAW_HIGH_MOTOR = 0;

#endif